[platformio]
default_envs = uno

[env]
framework = arduino
monitor_speed = 115200


lib_deps = marcoschwartz/LiquidCrystal_I2C

[env:uno]
platform = atmelavr
board = uno
upload_port = COM7
monitor_port = COM7

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328