[platformio]
default_envs = esp32dev1

[env]
framework = arduino
monitor_speed = 57600

lib_deps = marcoschwartz/LiquidCrystal_I2C

[env:uno]
platform = atmelavr
board = uno
upload_port = COM12
monitor_port = COM12

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
upload_port = COM12
monitor_port = COM12

[env:nanoatmega328old]
platform = atmelavr
board = nanoatmega328
upload_port = COM12
monitor_port = COM12

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
upload_port = COM12
monitor_port = COM12

[env:esp32dev1]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 57600
board_build.flash_mode = dio
